[package]
name = "bity-8"
version = "0.1.0"
publish = false

[lib]
name = "bity_8"

[dependencies]
hlua = "0.3"
rand = "0.5"
bresenham = "0.1.1"

[dependencies.sdl2]
version = "0.31"
features = ["gfx"]
