#!/usr/bin/env python3
# hex file to binary
import argparse
import re

def stripComments(string):
    string = re.sub(re.compile("#.*?\n" ) ,"" ,string)
    return string

def arg_logic():
    parser = argparse.ArgumentParser(prog="hex-to-bin",description = "Converts some ascii hex to a binary file. Ignores whitespace.")
    parser.add_argument("input",  help="File to read from.")
    parser.add_argument("output", help="File to write to.")
    return parser.parse_args()

args = arg_logic()

data = ""
with open(args.input, 'r') as f:
    data=stripComments(f.read()).replace('\n', '').replace(' ', '').replace('\t', '')

print("working...")
print(data)

with open(args.output, 'wb') as f:
    f.write(bytes.fromhex(data))
